### ISSUE TITLE
Make it possible to include generated pgf's

### ISSUE THREAD

**Issue by fredrike** [robjstan/tikzmagic#1]
I'm using the `tikzDevice` library for R in my jypyter notebook. However that does not produce a inline figure hence, would I like to include the generated `tikz file` and display it. 

Is that possible with tikzmagic?

**Comment by fredrike** [comment]
Here is a suggestion for such a patch, let me know if it is ok and I'll submit a pull-request.

    diff --git a/tikzmagic/tikzmagic.py b/tikzmagic/tikzmagic.py
    index 0489313..ef3af7b 100644
    --- a/tikzmagic/tikzmagic.py
    +++ b/tikzmagic/tikzmagic.py
    @@ -7,6 +7,7 @@ import tempfile
     from argparse import ArgumentParser
     from base64 import b64encode
     from os.path import isfile
    +from os import getcwd
     
     from IPython.core.magic import register_cell_magic
     from IPython.core.display import Image
    @@ -22,6 +23,16 @@ LATEX_TEMPLATE = r'''
         \end{{tikzpicture}}
         \end{{document}}'''
     
    +LATEX_TEMPLATE_INPUT = r'''
    +    \documentclass[tikz,border={border}]{{standalone}}
    +    \usepackage{{tikz,{latex_pkgs}}}
    +    \usetikzlibrary{{{tikz_libs}}}
    +    {latex_pre}
    +    \begin{{document}}
    +    {content}
    +    \input{{{input_file}}}
    +    \end{{document}}'''
    +
     @register_cell_magic
     def tikz(line, cell):
         '''Format TikZ commands into a LaTeX document, compile, and convert.'''
    @@ -29,6 +40,8 @@ def tikz(line, cell):
         parser.add_argument('-p', '--latex_packages', default='')
         parser.add_argument('-x', '--latex_preamble', default='')
         parser.add_argument('-l', '--tikz_libraries', default='')
    +    parser.add_argument('-i', '--input_file', default='')
         parser.add_argument('-s', '--scale', default=1, type=float)
         parser.add_argument('-b', '--border', default=4)
         args = parser.parse_args(shlex.split(line))
    @@ -37,6 +50,11 @@ def tikz(line, cell):
         latex = LATEX_TEMPLATE.format(content=cell, border=args.border, latex_pre=args.latex_preamble,
                                       latex_pkgs=args.latex_packages, tikz_libs=args.tikz_libraries)
     
    +    if(args.input_file != ''):
    +        latex = LATEX_TEMPLATE_INPUT.format(content=cell, border=args.border, latex_pre=args.latex_preamble,
    +                                      input_file=getcwd() + "/" +  args.input_file,
    +                                      latex_pkgs=args.latex_packages, tikz_libs=args.tikz_libraries)
    +
         # compile and convert, returning Image data
         return latex2image(latex, density=int(args.scale*300))

**Comment by robjstan** [comment]
Thanks for the patch, I've altered the logic slightly and committed a updated version that should be live now.

I also changed it to allow the line magic `%tikz -i test.tikz` to get the same result.

**Comment by fredrike** [comment]
Great work thank you!

But, what if I like to set some parameters (in my case i like to set `\sffamily` before input to get the right font for my figures). Or, perhaps can I set that in `{latex_pre}`.

I did like the old option of exporting to figure (preferable keeping the pdf) too (too bad you didn't keep that option).

**Comment by robjstan** [comment]
On the first point– for a cell magic, the contents of the cell still gets included before the input file, e.g.:
```
%%tikz -i example.tikz
\tikzset{every node/.style={font=\sffamily,white}}
```
(The output of this is shown in the [example notebook](https://github.com/robjstan/tikzmagic/blob/master/example.ipynb).)

Also note that you'll need to set the tikzdevice option `bareBones=True` to stop it also wrapping the plot in a `tikzpicture`.

I'll look into options to allow exporting the pdf figure.

**Comment by fredrike** [comment]
In my case are my `tikzpictures` wrapped in a `tikzpicture` environment (that is the whole reason for the suggested feature). 

This fixes it though.

    diff --git a/tikzmagic/tikzmagic.py b/tikzmagic/tikzmagic.py
    index 19ee85f..ac4bd07 100644
    --- a/tikzmagic/tikzmagic.py
    +++ b/tikzmagic/tikzmagic.py
    @@ -18,9 +18,7 @@ LATEX_TEMPLATE = r'''
         \usetikzlibrary{{{tikz_libs}}}
         {latex_pre}
         \begin{{document}}
    -    \begin{{tikzpicture}}
         {content}
    -    \end{{tikzpicture}}
         \end{{document}}'''
     
     @register_line_cell_magic
    @@ -39,6 +37,8 @@ def tikz(line, cell=''):
         if args.input_file:
             # add content from input_file before rest of cell
             cell += r'\input{{{cwd}/{input_file}}}'.format(cwd=getcwd(), input_file=args.input_file)
    +    else:
    +        cell = r'\begin{{tikzpicture}}{content}\end{{tikzpicture}}'.format(content=cell)
     
         latex = LATEX_TEMPLATE.format(content=cell, border=args.border, latex_pre=args.latex_preamble,
                                       latex_pkgs=args.latex_packages, tikz_libs=args.tikz_libraries)


This works great for me `%tikz -i sample.pgf -x "\renewcommand\familydefault{\sfdefault}"` with my patch and `sample.pgf` using a `tikzpicture` environment.

**Comment by fredrike** [comment]
Also, found this http://www.cityinthesky.co.uk/opensource/pdf2svg/ would it be an option to convert to svg instead (keeping the vector propterties).

**Comment by robjstan** [comment]
Ok – new options:

- `--no-wrap` removes the tikzpicture environment from the template. (Or set the tikzdevice option `bareBones=True` to remove it from your exported tikz.)
- `--export_file=<file.pdf>` also exports the PDF to the named file.
- `--debug` prints the LaTeX which will be compiled.

Let me know if anything still doesn't work!

I'll have a look at SVG support another time – can you open another new issue?
